### ISSUE TITLE
如何将图片上传到S3？

### ISSUE THREAD

**Issue by azataiot** [pylixm/django-mdeditor#167]
我现在的项目使用 django-storage 将static 文件都放到了s3 上面， 但是发现django-mdeditor 并不会将图片上传到s3

**Comment by azataiot** [comment]
如果需要改功能可以参考我提交的PR [#168 ]（#168）

**Comment by Sqvall** [comment]
Hello.

Sorry, but why we trying manual management this process, if django has special api `default_storage` for this.

If we will use it for file uploading we can:
- Remove config parameters like `upload_to_S3` and `s3_check_existence`, because uploader will inherit common behavior from `settings.py`.
- Brake dependencies from concrete implementation storage.
- Improve integration with `django-storage` because use `default_storage` we inherit correct processing for settings like this https://django-storages.readthedocs.io/en/latest/backends/amazon-S3.html

Im prepare PR #173 
For you could check it out.

Or correct me if I'm wrong in my hypothesis.

**Comment by azataiot** [comment]
> Hello.
> 
> Sorry, but why we trying manual management this process, if django has special api `default_storage` for this.
> 
> If we will use it for file uploading we can:
> 
> * Remove config parameters like `upload_to_S3` and `s3_check_existence`, because uploader will inherit common behavior from `settings.py`.
> * Brake dependencies from concrete implementation storage.
> * Improve integration with `django-storage` because use `default_storage` we automatically inherit correct processing for settings like `DEFAULT_FILE_STORAGE` https://django-storages.readthedocs.io/en/latest/backends/amazon-S3.html
> 
> Im prepare PR #173 For you could check it out.
> 
> Or correct me if I'm wrong in my hypothesis.

I believe this is more general and beautiful solution, yet I am still checking whether it works with some special cases.
